backend:
  name: git-gateway
  branch: master
media_folder: "_site/assets"
public_folder: "/assets/"
collections : 
  - name: "blog"
    label: "Blog"
    folder: "_site"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
  - { label : "Title", name: "title", widget: "string" }
  - { label : "Author", name: "author", widget: "string" }
  - { label : "Date", name: "date", widget: "datetime" }